### ISSUE TITLE
Conflict with project.nvim

### ISSUE THREAD

**Issue by ghost** [ellisonleao/dotenv.nvim#2]
First of all, thanks for developing this plugin.

I ran into an issue with this plugin when combined with project.nvim. Project.nvim uses the "BufEnter" event, which runs after the "BufReadPost" event, which is what dotenv.nvim currently uses. Because of this, dotenv.nvim is not able to know about a directory change that project.nvim performs with the "BufEnter" event.

I got around this by telling dotenv.nvim to not automatically load the `.env` file (which just disables the registering of the builtin autocmd) and instead defined my own autocmd but used the "BufEnter" event. This seems to allow dotenv.nvim to be aware of project.nvim's directory switching.

Because I have a workaround, I don't necessarily need the plugin to change. However, I wanted to bring this to your attention as others may encounter this.

**Comment by ghost** [comment]
```lua
--- current dotenv.nvim code
if dotenv.config.enable_on_load then
    local group = vim.api.nvim_create_augroup("Dotenv", { clear = true })
    vim.api.nvim_create_autocmd("BufReadPost", { group = group, pattern = "*", callback = dotenv.autocmd })
  end
```

Here is my workaround:
```lua
--- disable enable_on_load
        require('dotenv').setup({
          enable_on_load = false, -- will load your .env file upon loading a buffer
          verbose = true,         -- show error notification if .env file is not found and if .env is loaded
        }

```

```lua
-- custom autocmd with 'BufEnter' event
local group = vim.api.nvim_create_augroup("Dotenv", { clear = true })
vim.api.nvim_create_autocmd("BufEnter",
  { group = group, pattern = "*", callback = require("dotenv").autocmd })

```

**Comment by tan-wei** [comment]
The workaound works.

**Comment by ellisonleao** [comment]
#5 probably fix this too, will work on getting it merged soon
